apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  # namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
      #  1. option ENV
        env:
        - name: {VARIABLE_NAME}
          value: {CUSTOM_VALUE}     
      #  2. option ENV
        env:
        - name: {VARIABLE_NAME}
          valueFrom:
            configMapKeyRef:
              name: {confimap_name}
              key: {VARIABLE_NAME}
      #  3. option ENV - naming is required to be the same.
        envFrom:
        - configMapRef:
            name: {confimap_name}
      #  1. option SECRET
        env:
        - name: {VARIABLE_NAME}
          valueFrom:
            secretKeyRef:
              name: {secret_name}
              key: {VARIABLE_NAME}            
      #  2. option SECRET - naming is required to be the same.
        envFrom:
        - secretRef:
            name: {secret_name}
