apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller-minio
  namespace: storage
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port:
              number: 9001
