apiVersion: v1
kind: PersistentVolume
metadata:
  name: 500m
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/fullstack-project"
    type: DirectoryOrCreate
